const usuarios = [
  {
    id: 1,
    nombre: "Ana García",
    email: "ana.garcia@example.com",
    edad: 28,
    activo: true,
    ciudad: "Madrid",
    nivel: "Junior",
    hobbies: ["Lectura", "Senderismo", "Cocina"],
  },
  {
    id: 2,
    nombre: "Luis Martínez",
    email: "luis.martinez@example.com",
    edad: 45,
    activo: false,
    ciudad: "Barcelona",
    nivel: "Senior",
    hobbies: ["Fotografía", "Viajar"],
  },
  {
    id: 3,
    nombre: "Sofía Pérez",
    email: "sofia.perez@example.com",
    edad: 22,
    activo: true,
    ciudad: "Valencia",
    nivel: "Trainee",
    hobbies: ["Videojuegos", "Series", "Lectura"],
  },
  {
    id: 4,
    nombre: "Javier López",
    email: "javier.lopez@example.com",
    edad: 35,
    activo: true,
    ciudad: "Madrid",
    nivel: "Mid",
    hobbies: ["Cocina", "Fútbol", "Senderismo"],
  },
  {
    id: 5,
    nombre: "Elena Rodríguez",
    email: "elena.rodriguez@example.com",
    edad: 50,
    activo: false,
    ciudad: "Sevilla",
    nivel: "Senior",
    hobbies: ["Jardinería", "Lectura"],
  },
  {
    id: 6,
    nombre: "David Fernández",
    email: "david.fernandez@example.com",
    edad: 30,
    activo: true,
    ciudad: "Barcelona",
    nivel: "Mid",
    hobbies: ["Programación", "Senderismo"],
  },
];

export const productos = [
  {
    id: 101,
    nombre: "Laptop Pro",
    categoria: "Electrónica",
    precio: 1200.0,
    stock: 15,
    valoracion: 4.8,
  },
  {
    id: 102,
    nombre: "Teclado Mecánico",
    categoria: "Electrónica",
    precio: 85.5,
    stock: 50,
    valoracion: 4.5,
  },
  {
    id: 103,
    nombre: "Camiseta Algodón",
    categoria: "Ropa",
    precio: 25.0,
    stock: 120,
    valoracion: 3.9,
  },
  {
    id: 104,
    nombre: "Pantalón Vaquero",
    categoria: "Ropa",
    precio: 65.99,
    stock: 40,
    valoracion: 4.2,
  },
  {
    id: 105,
    nombre: "Smartphone Lite",
    categoria: "Electrónica",
    precio: 450.0,
    stock: 30,
    valoracion: 4.1,
  },
  {
    id: 106,
    nombre: "Libro de Ficción",
    categoria: "Libros",
    precio: 18.5,
    stock: 200,
    valoracion: 4.7,
  },
  {
    id: 107,
    nombre: "Auriculares Inalámbricos",
    categoria: "Electrónica",
    precio: 150.0,
    stock: 25,
    valoracion: 4.6,
  },
  {
    id: 108,
    nombre: "Vestido de Verano",
    categoria: "Ropa",
    precio: 45.0,
    stock: 75,
    valoracion: 3.5,
  },
];